//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDetail
    {
        public int ItemId { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<long> SerialNo { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<long> Rate { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
